# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  NodeCount = 3

  (1..NodeCount).each do |i|
    config.vm.define "ubuntuvm#{i}" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "ubuntuvm#{i}.example.com"
      node.vm.network "private_network", ip: "192.168.100.2#{i}"
      node.vm.provision "shell", path: "servidorw2.sh"
      node.vm.provider "virtualbox" do |v|
        v.name = "ubuntuvm#{i}"
        v.memory = 1028
        v.cpus = 1
      end
    end
  end

end
